# Generated by Django 3.1.6 on 2021-02-24 15:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_member', models.BooleanField(default=False)),
                ('is_tour_arranger', models.BooleanField(default=False)),
                ('is_resorts_manager', models.BooleanField(default=False)),
                ('is_car_driver', models.BooleanField(default=False)),
                ('is_blogger', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='blogger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parjatan_ui.user')),
                ('user_type', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='car_driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parjatan_ui.user')),
                ('user_type', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parjatan_ui.user')),
                ('user_type', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='resorts_manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parjatan_ui.user')),
                ('user_type', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tour_arranger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parjatan_ui.user')),
                ('user_type', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parjatan_ui.user')),
                ('image', models.ImageField(upload_to='uploaded_image/user')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('total_memeber', models.IntegerField()),
                ('booked_seat', models.IntegerField()),
                ('age_limit', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('duration_nights', models.IntegerField()),
                ('date', models.DateField()),
                ('slider_img1', models.ImageField(upload_to='uploaded_image/slider')),
                ('slider_img2', models.ImageField(upload_to='uploaded_image/slider')),
                ('slider_img3', models.ImageField(upload_to='uploaded_image/slider')),
                ('slider_img4', models.ImageField(upload_to='uploaded_image/slider')),
                ('highlight_1', models.CharField(max_length=150)),
                ('highlight_2', models.CharField(max_length=150)),
                ('highlight_3', models.CharField(max_length=150)),
                ('highlight_4', models.CharField(max_length=150)),
                ('highlight_5', models.CharField(max_length=150)),
                ('tour_plan', models.TextField()),
                ('promo_text', models.TextField()),
                ('inc_accommodation', models.TextField()),
                ('inc_transportation', models.TextField()),
                ('inc_meals', models.TextField()),
                ('inc_guid', models.TextField()),
                ('inc_additional', models.TextField()),
                ('tour_contact_phone', models.CharField(max_length=150)),
                ('tour_contact_email', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
