# Generated by Django 3.1.6 on 2021-02-19 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parjatan_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('total_memeber', models.IntegerField()),
                ('booked_seat', models.IntegerField()),
                ('age_limit', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('duration_nights', models.IntegerField()),
                ('date', models.DateField()),
                ('slider_img1', models.ImageField(upload_to='uploaded_image/slider')),
                ('slider_img2', models.ImageField(upload_to='uploaded_image/slider')),
                ('slider_img3', models.ImageField(upload_to='uploaded_image/slider')),
                ('slider_img4', models.ImageField(upload_to='uploaded_image/slider')),
                ('highlight_1', models.CharField(max_length=150)),
                ('highlight_2', models.CharField(max_length=150)),
                ('highlight_3', models.CharField(max_length=150)),
                ('highlight_4', models.CharField(max_length=150)),
                ('highlight_5', models.CharField(max_length=150)),
                ('tour_plan', models.TextField()),
                ('inc_accommodation', models.TextField()),
                ('inc_transportation', models.TextField()),
                ('inc_meals', models.TextField()),
                ('inc_guid', models.TextField()),
                ('inc_additional', models.TextField()),
                ('tour_contact_phone', models.CharField(max_length=150)),
                ('tour_contact_email', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
